const WALLET_STATUS = {
  ACTIVE: 'ACTIVE',
  FROZEN: 'FROZEN',
};

const TRANSACTION_TYPE = {
  INTERNAL: 'INTERNAL',
  EXTERNAL: 'EXTERNAL',
  REVERSAL: 'REVERSAL',
};

const TRANSACTION_STATUS = {
  INITIATED: 'INITIATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
};

const LEDGER_ENTRY_TYPE = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT',
};

const AUDIT_ACTION = {
  WALLET_CREATED: 'WALLET_CREATED',
  TRANSFER_INITIATED: 'TRANSFER_INITIATED',
  TRANSFER_SUCCESS: 'TRANSFER_SUCCESS',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  REVERSAL_CREATED: 'REVERSAL_CREATED',
  EXTERNAL_WEBHOOK_RECEIVED: 'EXTERNAL_WEBHOOK_RECEIVED',
};

module.exports = {
  WALLET_STATUS,
  TRANSACTION_TYPE,
  TRANSACTION_STATUS,
  LEDGER_ENTRY_TYPE,
  AUDIT_ACTION,
};
